### ISSUE TITLE
Change types of conversions and reads

### ISSUE THREAD

**Issue by kubitre** [kostya05983/rest-bomber#14]
In this case is returning string:
https://github.com/kostya05983/rest-bomber/blob/5cd8163ad571c3dc1a0d9454416d1b885991b1ad/parser/readers.go#L18-L31

but where this method is called, the conversion to a slice is used byte:
https://github.com/kostya05983/rest-bomber/blob/5cd8163ad571c3dc1a0d9454416d1b885991b1ad/parser/parser.go#L23

**Comment by kostya05983** [comment]
Yes, I think we need to fix it
