### ISSUE TITLE
SendMetrics to Server

### ISSUE THREAD

**Issue by kostya05983** [kostya05983/rest-bomber#18]
one of format, you can imagine yours
{
times: [123,213,234],
date: 24.05.16 18.30
}
times numbers in ms
you can add others attributes, one time means request/response time.

**Comment by kubitre** [comment]
complete in branch `new_bomber`

**Comment by kubitre** [comment]
На текущий момент, в качестве метрик вижу следующее: 
Время затраченное на каждую стадию в сценарии
Время выполнения всех стадий
